---
- name: Set metricbeat_version to last version
  set_fact:
    metricbeat_version: '{{ metricbeat_last_version }}'
  when: metricbeat_version.find('.x') == 1

- name: Create temporary build directory
  win_file:
    state: directory
    path: '{{ win_download_path }}'

- name: Setup path folders
  win_file:
    path: '{{ path_folder.value }}'
    state: directory
  with_dict: '{{ path }}'
  loop_control:
    loop_var: path_folder

- name: Download metricbeat
  win_get_url:
    url: 'https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-{{ metricbeat_version }}-windows-x86_64.zip'
    dest: '{{ win_download_path }}\metricbeat.zip'
    force: false
  register: download_win_package
  until: download_win_package is succeeded

- name: Unzip metricbeat
  win_unzip:
    src: '{{ win_download_path }}/metricbeat.zip'
    dest: '{{ win_download_path }}'
    creates: '{{ win_download_path }}/metricbeat-{{ metricbeat_version }}-windows-x86_64'

- name: Copy files to home directory
  win_copy:
    src: '{{ win_download_path }}/metricbeat-{{ metricbeat_version }}-windows-x86_64/'
    dest: '{{ path.home }}/'
    force: false
    remote_src: true
  notify: Restart metricbeat win

- name: Templating metricbeat configuration
  win_template:
    src: '{{ mb_path_file.src }}'
    dest: '{{ mb_path_file.dst }}'
  loop:
    - src: metricbeat.yml.j2
      dst: '{{ path.config }}\metricbeat.yml'
    - src: metricbeat-template.bat.j2
      dst: '{{ path.home }}\metricbeat.bat'
  loop_control:
    loop_var: mb_path_file
  notify: Restart metricbeat win

- name: Install nssm
  win_chocolatey:
    name: nssm
    state: present

- name: Create service via nssm
  win_nssm:
    name: '{{ metricbeat_service_name }}'
    application: '{{ path.home }}\metricbeat.bat'
    state: present
  notify: Restart metricbeat win

- name: Ensure that metricbeat path present in 'Path' variable
  win_path:
    elements: '{{ path.home }}'
    state: present
    scope: machine

- name: Start a service
  win_service:
    name: '{{ metricbeat_service_name }}'
    state: started
