---
- name: Include common prepare
  import_playbook: ../resources/provisioning/AWS/prepare.yml

- name: Prepare Debian
  hosts: debian_family
  become: true
  tasks:

    - name: Add universe repository for bionic
      apt_repository:
        repo: deb http://archive.ubuntu.com/ubuntu bionic universe
        state: present
      when: ansible_distribution_release == 'bionic'

    - name: Install python packages
      apt:
        name:
          - python3-apt
        state: present
      register: status
      until: status is succeeded
